Math magicians: components
musangamfure/math-magicians-app pull request #2
Opened 2023-05-30 21:28 UTC by musangamfure

**Hello,** 

In this PR, I have worked on the calculator component feature.

**These are what I have achieved:**

- [ ] Create a new directory called `components`
- [ ] Inside components, create a new Calculator.js file for JSX and Calculator.css for styling
- [ ] Use functional components
- [ ] Create at least 1 child component

Kindly check and let me know what you think.

**Best regards.**

Happy Coding🎉

2023-05-30 22:17 UTC, emmanuellekamwa requested changes
**STATUS: CHANGES REQUESTED ⛔🛑❌**
Hello @musangamfure 👋
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Good commit messages.
- Descriptive PR.

## Required Changes ♻️
_Check the comments under the review._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-30 22:17 UTC, emmanuellekamwa commented on src/components/calculator.js
> +      +
- [ ] The calculator component should be a functional component. Please kindly apply that.

2023-05-30 22:17 UTC, emmanuellekamwa commented on README.md
- [ ] The live demo link is not functioning well. You can either remove it or fix it.

2023-05-31 05:53 UTC, musangamfure commented on src/components/calculator.js
> +      +
Hello, @emmanuellekamwa 

I thought🤔 arrow functions are also allowed as a functional component. but Le me change it as per your suggestion.

Thanks again for your insights.

2023-05-31 05:54 UTC, musangamfure commented on README.md
Ok. I will remove it Immediately

2023-05-31 06:00 UTC, wayungi commented on src/components/calculator.js
> +      +
@musangamfure, arrow functions are indeed functional components. I liked your attitude and response to this request.

2023-05-31 06:01 UTC, wayungi commented on README.md
Good work fixing this ✔️

2023-05-31 06:03 UTC, wayungi approved these changes
Hi @musangamfure , 

![image](https://user-images.githubusercontent.com/99656687/220082459-c1b049c7-5498-42e7-942b-ec7a05d3e603.png)

Great work, your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

**Remember: Every finish line 🏁  is the beginning of a new race 🐎** 

## Highlights
- [ ] All requested changes implemented 🏁 
- [ ] Correct Gitflow used 🏁 
- [ ] Good PR title & description 🏁 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-31 06:16 UTC, musangamfure commented on src/components/calculator.js
> +      +
Hello @wayungi 

Thank you so much for your clarification. Is there any other reason why @emmanuellekamwa asked me to change the code to use a normal function?

2023-05-31 06:19 UTC, musangamfure commented
Hello @wayungi 

Thank you so much🙌🎉 for approving my PR. And your helpful insights.

2023-05-31 06:19 UTC, merged

2023-05-31 06:23 UTC, wayungi commented on src/components/calculator.js
> +      +
I don't know why she made the request but I think it's based on her interpretation of the project requirements. It's always good to engage your reviewers in case you hold a different opinion from what they have suggested. This helps both of you to learn from the interaction and become better programmers.

2023-05-31 06:31 UTC, musangamfure commented on src/components/calculator.js
> +      +
Thanks for your helpful suggestions. I do as you suggested